//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sogeti.App.Specs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReferenceOutputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReferenceOutputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sogeti.App.Specs.ReferenceOutputs", typeof(ReferenceOutputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File missingFile.csv not found in the file system..
        /// </summary>
        internal static string FileNotFoundOutput {
            get {
                return ResourceManager.GetString("FileNotFoundOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3, fname3 lname3, http://link-3, 2003-12-31, 2004-12-31, party1, portrait3, thumbnail3, New York
        ///Total count: 4..
        /// </summary>
        internal static string NoFilterOutput {
            get {
                return ResourceManager.GetString("NoFilterOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2, fname2 lname2, http://link-2, 2003-12-31, 2004-12-31, party2, portrait2, thumbnail2, homeState2
        ///Total count: 2..
        /// </summary>
        internal static string RealOutput {
            get {
                return ResourceManager.GetString("RealOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2, fname2 lname2, http://link-2, 2003-12-31, 2004-12-31, party2, portrait2, thumbnail2, homeState2
        ///Total count: 2..
        /// </summary>
        internal static string WithStateFilterOutput {
            get {
                return ResourceManager.GetString("WithStateFilterOutput", resourceCulture);
            }
        }
    }
}
